version: "3.7"
services:
  jdownloader2:
    image: jlesage/jdownloader-2
    container_name: jdownloader-2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
      - UMASK_SET=022 #optional
    volumes:
      - /docker/docker-images-data/jdownloader2_data_dir/descargas:/output
      - /docker/docker-images-data/jdownloader2_data_dir/config:/config
    ports:
      - 5800:5800
    restart: always
    networks:
      - frontend
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - traefik.enable=true # <== Enable traefik to proxy this container
      # URL HTTP
      - traefik.http.routers.jdownloader2.rule=Host(`jdownloader2.palominoia.com`) # <== Your Domain Name goes here for the http rule
      # Point d HTTP
      - traefik.http.routers.jdownloader2.entrypoints=http
      # Utilisation du middleware pour redirigé l'HTTP vers l'HTTPS
      - traefik.http.routers.jdownloader2.middlewares=redirect@file
      # Load balancer
      - traefik.http.services.jdownloader2.loadbalancer.server.port=5800
      # URL HTTPS
      - traefik.http.routers.jdownloader2-secured.rule=Host(`jdownloader2.palominoia.com`)
      # Point  HTTPS
      - traefik.http.routers.jdownloader2-secured.entrypoints=https
      # Activation de TLS
      - traefik.http.routers.jdownloader2-secured.tls=true
      - traefik.docker.network=frontend
      
networks:
  frontend:
    external:
      name: frontend
