# traefik/traefik.config.toml
[http.middlewares]
  [http.middlewares.redirect.redirectscheme]
    scheme = "https"

[tls]
  [[tls.certificates]]
    certFile = "/etc/certs/palominoia.com+4.pem"
    keyFile = "/etc/certs/palominoia.com+4-key.pem"